
--1. Bài tập 1
--Sinh viên cài đặt hoàn chỉnh bằng các câu lệnh SQL cho 2 CSDL
--QuanLyBanHang (Phần I, câu 1 bài tập thực hành trang 3) và
--QuanLyGiaoVu (Phần I, câu 1 bài tập thực hành trang 11).
GO
USE master
IF EXISTS (SELECT * FROM SYS.DATABASES WHERE NAME = 'QUANLYBANHANG')
BEGIN
	DROP DATABASE QUANLYBANHANG;
END
GO
CREATE DATABASE QUANLYBANHANG
GO

USE QUANLYBANHANG
GO

CREATE TABLE KHACHHANG
(
	MAKH CHAR(4) PRIMARY KEY, 
	HOTEN VARCHAR(40) NOT NULL,
	DCHI VARCHAR(50) NOT NULL,
	SODT VARCHAR(20) NOT NULL,
	NGSINH SMALLDATETIME,
	NGDK SMALLDATETIME,
	DOANHSO MONEY NOT NULL
)
GO
CREATE TABLE NHANVIEN
(
	MANV CHAR(4) PRIMARY KEY,
	HOTEN VARCHAR(40) NOT NULL,
	SODT VARCHAR(20) NOT NULL,
	NGVL SMALLDATETIME
)
GO
CREATE TABLE SANPHAM
(
	MASP CHAR(4) PRIMARY KEY,
	TENSP VARCHAR(40) NOT NULL,
	DVT VARCHAR(20),
	NUOCSX VARCHAR(40),
	GIA MONEY NOT NULL
)
GO
CREATE TABLE HOADON
(
	SOHD INT PRIMARY KEY,
	NGHD SMALLDATETIME,
	MAKH CHAR(4) FOREIGN KEY REFERENCES KHACHHANG(MAKH),
	MANV CHAR(4) FOREIGN KEY REFERENCES NHANVIEN(MANV),
	TRIGIA MONEY
)
GO
CREATE TABLE CTHD
(
	SOHD INT FOREIGN KEY REFERENCES HOADON(SOHD),
	MASP CHAR(4) FOREIGN KEY REFERENCES SANPHAM(MASP),
	SL INT,
	PRIMARY KEY (SOHD, MASP)
)
GO

--------------------------------------------------------------------------------------------------------------------
--2. Bài tập 2
--Sinh viên hoàn thành Phần I bài tập QuanLyBanHang từ câu 2 đến câu 10.

ALTER TABLE SANPHAM ADD GHICHU VARCHAR(20)
GO

ALTER TABLE KHACHHANG ADD LOAIKH TINYINT
GO

ALTER TABLE SANPHAM ALTER COLUMN GHICHU VARCHAR(100)
GO

ALTER TABLE SANPHAM DROP COLUMN GHICHU
GO

ALTER TABLE KHACHHANG ALTER COLUMN LOAIKH VARCHAR(20)
GO

ALTER TABLE SANPHAM ADD CONSTRAINT CK_DVT CHECK(DVT in ('cay', 'hop', 'cai', 'quyen', 'chuc'))
GO

ALTER TABLE SANPHAM ADD CONSTRAINT CK_GIA CHECK(GIA >= 500)
GO

ALTER TABLE CTHD ADD CONSTRAINT CK_SL CHECK(SL >= 1)
GO

ALTER TABLE KHACHHANG ADD CONSTRAINT CK_NGDK CHECK(NGDK > NGSINH)
 GO

---------------------------------------------------------------------------------------------------------------------------

USE master
IF EXISTS (SELECT * FROM SYS.DATABASES WHERE NAME = 'QUANLYHOCVU')
BEGIN
	DROP DATABASE QUANLYHOCVU;
END
GO

CREATE DATABASE QUANLYHOCVU
GO

USE QUANLYHOCVU
GO

CREATE TABLE KHOA
(
	MAKHOA VARCHAR(4) PRIMARY KEY,
	TENKHOA VARCHAR(40),
	NGTLAP SMALLDATETIME,
	TRGKHOA CHAR(4)
)
GO

CREATE TABLE MONHOC
(
	MAMH VARCHAR(10) PRIMARY KEY,
	TENMH VARCHAR(40),
	TCLT TINYINT,
	TCTH TINYINT,
	MAKHOA VARCHAR(4) FOREIGN KEY REFERENCES KHOA(MAKHOA)
)
GO

CREATE TABLE DIEUKIEN
(
	MAMH VARCHAR(10) FOREIGN KEY REFERENCES MONHOC(MAMH),
	MAMH_TRUOC VARCHAR(10),
	PRIMARY KEY (MAMH, MAMH_TRUOC)
)
GO

CREATE TABLE GIAOVIEN
(
	MAGV CHAR(4) PRIMARY KEY,
	HOTEN VARCHAR(40),
	HOCVI VARCHAR(10),
	HOCHAM VARCHAR(10),
	GIOITINH VARCHAR(3),
	NGSINH SMALLDATETIME,
	NGVL SMALLDATETIME,
	HESO NUMERIC(4,2),
	MUCLUONG MONEY,
	MAKHOA VARCHAR(4) FOREIGN KEY REFERENCES KHOA(MAKHOA)
)
GO

CREATE TABLE LOP
(
	MALOP CHAR(3) PRIMARY KEY,
	TENLOP VARCHAR(40),
	TRGLOP CHAR(5),
	SISO TINYINT,
	MAGVCN CHAR(4) FOREIGN KEY REFERENCES GIAOVIEN(MAGV)
)
GO

CREATE TABLE HOCVIEN
(
	MAHV CHAR(5) PRIMARY KEY,
	HO VARCHAR(40),
	TEN VARCHAR(10),
	NGSINH SMALLDATETIME,
	GIOITINH VARCHAR(3),
	NOISINH VARCHAR(40),
	MALOP CHAR(3) FOREIGN KEY REFERENCES LOP(MALOP) 
)
GO

CREATE TABLE GIANGDAY
(
	MALOP CHAR(3) FOREIGN KEY REFERENCES LOP(MALOP),
	MAMH VARCHAR(10) FOREIGN KEY REFERENCES MONHOC(MAMH),
	MAGV CHAR(4) FOREIGN KEY REFERENCES GIAOVIEN(MAGV),
	HOCKY TINYINT,
	NAM SMALLINT,
	TUNGAY SMALLDATETIME,
	DENNGAY SMALLDATETIME,
	PRIMARY KEY (MALOP, MAMH)
)
GO

CREATE TABLE KETQUATHI
(
	MAHV CHAR(5) FOREIGN KEY REFERENCES HOCVIEN(MAHV),
	MAMH VARCHAR(10) FOREIGN KEY REFERENCES MONHOC(MAMH),
	LANTHI TINYINT,
	NGTHI SMALLDATETIME,
	DIEM NUMERIC(4,2),
	KQUA VARCHAR(10),
	PRIMARY KEY (MAHV, MAMH, LANTHI)
)
GO

--------------------------------------------------------------------------------------------------------------------

--3. Bài tập 3
--Sinh viên hoàn thành Phần I bài tập QuanLyGiaoVu từ câu 3 đến câu 8.




ALTER TABLE GIAOVIEN ADD CONSTRAINT CK_GIOITINHGV CHECK(GIOITINH in ('Nam', 'Nu'))
GO 

ALTER TABLE HOCVIEN ADD CONSTRAINT CK_GIOITINHHV CHECK(GIOITINH in ('Nam', 'Nu'))
GO

 
ALTER TABLE KETQUATHI ADD CONSTRAINT CK_DIEM CHECK(DIEM BETWEEN 0 AND 10 AND LEN(SUBSTRING(CAST(DIEM AS VARCHAR),CHARINDEX('.',DIEM)+1,1000))>=2)
GO


ALTER TABLE KETQUATHI ADD CONSTRAINT CK_KQUA CHECK(KQUA = IIF(DIEM BETWEEN 5 AND 10, 'Dat','Khong dat'))
GO


ALTER TABLE KETQUATHI ADD CONSTRAINT CK_LANTHI CHECK(LANTHI<=3)
GO


ALTER TABLE GIANGDAY ADD CONSTRAINT CK_HOCKY CHECK(HOCKY BETWEEN 1 AND 3)
GO

ALTER TABLE GIAOVIEN ADD CONSTRAINT CK_HOCVI CHECK(HOCVI in ('CN','KS','Ths','TS','PTS'))
GO